services:
  temp-postgres:
    image: 'postgres:16'
    container_name: temp-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: temp_postgres